global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "ctfboard-monitor"

rule_files:
  - "/etc/prometheus/alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "backend"
    static_configs:
      - targets: ["backend:8080"]
    metrics_path: "/metrics"

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8180"]

  - job_name: "vault"
    metrics_path: "/v1/sys/metrics"
    params:
      format: ["prometheus"]
    static_configs:
      - targets: ["vault:8200"]

  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "seaweedfs"
    static_configs:
      - targets: ["seaweedfs:9324"]
    metrics_path: "/metrics"
